import Navbar from "../Navbar";

const TermsAndConditionsPage = () => {
  return (
    <div className="min-h-screen bg-gray-100">
      <Navbar />

      {/* Top Blue Section */}
      <div className="bg-[#123a63] h-20 w-full"></div>

      {/* Main Container */}
      <div className="max-w-6xl mx-auto px-6 -mt-10 pb-16">

        {/* White Card */}
        <div className="bg-white rounded-xl shadow-md p-10">

          <h1 className="text-3xl font-bold text-[#123a63] mb-6">
            Terms & Conditions
          </h1>

          <p className="text-gray-700 mb-6 leading-relaxed">
            This document is an electronic record in terms of the Information
            Technology Act, 2000 and rules thereunder as applicable and the
            amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>

          <p className="text-gray-700 mb-6 leading-relaxed">
            This document is published in accordance with the provisions of Rule
            3 (1) of the Information Technology (Intermediaries Guidelines)
            Rules, 2011 that require publishing the rules and regulations,
            privacy policy and Terms of Use for access or usage of the domain
            name, including the related mobile site and mobile application
            (hereinafter referred to as the “Platform”).
          </p>

          <p className="text-gray-700 mb-6 leading-relaxed">
            The Platform is owned and operated by the Platform Owner (details
            provided at the end of this document).
          </p>

          <p className="text-gray-700 mb-6 leading-relaxed">
            Your use of the Platform, its services, and tools are governed by
            the following terms and conditions (“Terms of Use”) including the
            applicable policies which are incorporated herein by way of
            reference. If you transact on the Platform, you shall be subject to
            the policies applicable for such transactions. By mere use of the
            Platform, you shall be contracting with the Platform Owner, and
            these Terms constitute your binding obligations.
          </p>

          <p className="text-gray-700 mb-6 leading-relaxed font-semibold">
            ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR
            AGREEMENT TO ALL THE TERMS AND CONDITIONS. PLEASE READ THEM
            CAREFULLY BEFORE PROCEEDING.
          </p>

          <h2 className="text-xl font-semibold text-[#123a63] mt-6 mb-3">
            Key Terms
          </h2>

          {/* 1 */}
          <h3 className="font-semibold mt-4">1. Eligibility & Registration</h3>
          <p className="text-gray-700 leading-relaxed">
            To access and use the Services, you agree to provide true, accurate,
            and complete information during and after registration, and you are
            responsible for all acts done through your registered account.
          </p>

          {/* 2 */}
          <h3 className="font-semibold mt-4">2. Accuracy of Information</h3>
          <p className="text-gray-700 leading-relaxed">
            Neither we nor any third parties provide any warranty or guarantee
            as to the accuracy, timeliness, performance, completeness, or
            suitability of the information and materials on this Platform. We
            exclude liability for inaccuracies to the fullest extent permitted
            by law.
          </p>

          {/* 3 */}
          <h3 className="font-semibold mt-4">3. Use of Services</h3>
          <p className="text-gray-700 leading-relaxed">
            Your use of our Services and Platform is solely at your own risk.
            You must independently assess and ensure that the Services meet your
            requirements.
          </p>

          {/* 4 */}
          <h3 className="font-semibold mt-4">4. Intellectual Property</h3>
          <p className="text-gray-700 leading-relaxed">
            The contents of the Platform including design, layout, graphics,
            and text are proprietary. You do not acquire any rights to our
            intellectual property.
          </p>

          {/* 5 */}
          <h3 className="font-semibold mt-4">5. Prohibited Use</h3>
          <p className="text-gray-700 leading-relaxed">
            You agree not to use the Platform or Services for unlawful purposes
            or in violation of Indian or local laws.
          </p>

          {/* 6 */}
          <h3 className="font-semibold mt-4">6. Links to Third Parties</h3>
          <p className="text-gray-700 leading-relaxed">
            The Platform may contain links to third-party websites. Accessing
            these will be governed by the respective terms and privacy policies
            of such third parties.
          </p>

          {/* 7 */}
          <h3 className="font-semibold mt-4">7. Legal Relationship</h3>
          <p className="text-gray-700 leading-relaxed">
            Initiating a transaction constitutes a legally binding contract
            between you and the Platform Owner.
          </p>

          {/* 8 */}
          <h3 className="font-semibold mt-4">8. Indemnity</h3>
          <p className="text-gray-700 leading-relaxed">
            You agree to indemnify and hold harmless the Platform Owner,
            affiliates, and employees against claims or damages arising out of
            your breach of these Terms.
          </p>

          {/* 9 */}
          <h3 className="font-semibold mt-4">9. Limitation of Liability</h3>
          <p className="text-gray-700 leading-relaxed">
            In no event will the Platform Owner be liable for indirect,
            incidental, or consequential damages. Liability shall not exceed the
            amount paid by you for the Services giving rise to the claim, or INR
            100, whichever is less.
          </p>

          {/* 10 */}
          <h3 className="font-semibold mt-4">10. Force Majeure</h3>
          <p className="text-gray-700 leading-relaxed">
            We are not liable for failure to perform obligations due to events
            beyond our reasonable control.
          </p>

          {/* 11 */}
          <h3 className="font-semibold mt-4">
            11. Governing Law & Jurisdiction
          </h3>
          <p className="text-gray-700 leading-relaxed">
            These Terms shall be governed by the laws of India. All disputes
            shall be subject to the exclusive jurisdiction of the courts
            specified below.
          </p>

          {/* 12 */}
          <h3 className="font-semibold mt-4">12. Communication</h3>
          <p className="text-gray-700 leading-relaxed">
            All concerns or communications relating to these Terms must be
            directed to the contact details provided below.
          </p>

          {/* Company Details */}
          <h2 className="text-xl font-semibold text-[#123a63] mt-8 mb-3">
            Company Details
          </h2>

          <div className="text-gray-700 space-y-1">
            <p><strong>Domain Name:</strong> https://pousadagetaways.com/</p>
            <p><strong>Company Name:</strong> POUSADA GETAWAYS</p>
            <p>
              <strong>Registered Office Address:</strong> Sterling Apartments,
              Vasudeva Dempo Road, Penha De Franca, North Goa, Goa, 403001
            </p>
            <p>
              <strong>Jurisdiction:</strong> Penha De Franca, Goa, India
            </p>
          </div>

        </div>
      </div>
    </div>
  );
};

export default TermsAndConditionsPage;